import Link from "next/link";
import { ArrowRight, ChartLineUp, MagicWand, QrCode, SplitHorizontal, Sparkle } from "@phosphor-icons/react/dist/ssr";
import { Nav } from "@/components/nav";
import { Badge, LinkButton, Panel } from "@/components/ui";
import { plans } from "@/lib/plans";

export default function Home() {
  const features = [
    [QrCode, "Campaign QR templates", "Restaurant menus, real estate signs, event flyers, gym promos, clinic intake, coupons, and lead capture links."],
    [MagicWand, "Scan-safe brand styling", "Create branded codes and frames without sacrificing scannability or print clarity."],
    [ChartLineUp, "Offline attribution", "Show which poster, flyer, sign, or table tent actually drove scans, leads, and conversions."],
    [SplitHorizontal, "Smart Redirect + offers", "Change destinations after printing, A/B test offers, and track conversion events without reprinting codes."],
  ];
  return <div className="min-h-[100dvh] bg-zinc-50 text-zinc-950 dark:bg-zinc-950 dark:text-zinc-50"><Nav />
    <main>
      <section className="mx-auto grid max-w-7xl gap-8 px-4 py-16 sm:px-6 lg:grid-cols-[0.95fr_1.05fr] lg:py-24">
        <div className="self-center"><Badge>Local campaign QR analytics</Badge><h1 className="mt-5 max-w-3xl text-5xl font-semibold leading-none tracking-tighter md:text-7xl">Turn every flyer, table tent, sign, and open house into a measurable campaign.</h1><p className="mt-6 max-w-[62ch] text-lg leading-relaxed text-zinc-600 dark:text-zinc-300">QRSpark is not another commodity QR generator. It helps restaurants, realtors, events, gyms, and clinics track offline-to-online campaigns with smart redirects, conversion pixels, and simple client-ready reporting.</p><div className="mt-8 flex flex-wrap gap-3"><LinkButton href="/dashboard/create" prefetch={false} className="gap-2">Build a campaign QR <ArrowRight size={18}/></LinkButton><Link href="/pricing" className="inline-flex min-h-10 items-center rounded-full border border-zinc-200 px-5 text-sm font-semibold dark:border-white/10">Compare plans</Link></div><div className="mt-7 flex flex-wrap gap-4 text-sm text-zinc-500"><span>Local-business focused</span><span>Dynamic redirects</span><span>Reports from $19/mo</span></div></div>
        <div className="relative"><div className="absolute -inset-4 rounded-[3rem] bg-emerald-500/10 blur-3xl"/><Panel className="relative grid gap-4 p-4 sm:p-6"><div className="grid gap-4 sm:grid-cols-[1fr_240px]"><div className="rounded-[1.75rem] border border-zinc-200 bg-zinc-50 p-4 dark:border-white/10 dark:bg-zinc-950"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-zinc-500">Prompt</p><p className="mt-3 text-2xl font-semibold tracking-tight">Track this table-tent QR: split traffic between menu A and offer B, then show scans and conversions by day.</p><div className="mt-5 h-2 w-2/3 rounded-full bg-zinc-200 dark:bg-zinc-800"/><div className="mt-3 h-2 w-1/2 rounded-full bg-zinc-200 dark:bg-zinc-800"/></div><div className="grid place-items-center rounded-[1.75rem] bg-white p-4 shadow-inner dark:bg-zinc-900"><div className="grid size-44 grid-cols-5 gap-1 rounded-2xl bg-white p-3 shadow-xl">{Array.from({ length: 25 }).map((_, i) => <span key={i} className={`rounded ${[0,1,2,5,10,11,12,14,17,20,22,23,24].includes(i) ? "bg-zinc-950" : "bg-emerald-100"}`}/>)}</div></div></div><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-3xl bg-zinc-950 p-4 text-white"><p className="text-3xl font-semibold">1,247</p><p className="text-sm text-zinc-400">scans</p></div><div className="rounded-3xl border border-zinc-200 p-4 dark:border-white/10"><p className="text-3xl font-semibold">7.8%</p><p className="text-sm text-zinc-500">conversion</p></div><div className="rounded-3xl border border-zinc-200 p-4 dark:border-white/10"><p className="text-3xl font-semibold">60/40</p><p className="text-sm text-zinc-500">A/B split</p></div></div></Panel></div>
      </section>
      <section id="ai-qr-art" className="mx-auto max-w-7xl px-4 py-10 sm:px-6"><div className="grid gap-4 lg:grid-cols-4">{features.map(([Icon, title, body]) => <Panel key={String(title)} className="p-6"><Icon size={28} weight="bold" className="text-emerald-600"/><h3 className="mt-5 text-xl font-semibold tracking-tight">{String(title)}</h3><p className="mt-2 text-sm leading-6 text-zinc-500">{String(body)}</p></Panel>)}</div></section>
      <section className="mx-auto max-w-7xl px-4 py-12 sm:px-6"><Panel className="grid gap-8 overflow-hidden bg-zinc-950 p-6 text-white dark:bg-white dark:text-zinc-950 lg:grid-cols-[0.8fr_1.2fr] lg:p-8"><div><Badge>Built for trust</Badge><h2 className="mt-4 text-4xl font-semibold tracking-tighter">A clean workspace, real data only, and a fast first win.</h2><p className="mt-4 text-sm leading-6 text-zinc-300 dark:text-zinc-600">New users start with an empty account. No fake QR rows, no inflated analytics, and no confusing sample campaigns inside the dashboard.</p></div><div className="grid gap-3 sm:grid-cols-3">{[["1", "Create", "Paste the destination and name the campaign."], ["2", "Print", "Download PNG, SVG, or PDF for flyers and table tents."], ["3", "Measure", "Scans and conversions populate only from your live traffic."]].map(([step,title,body]) => <div key={step} className="rounded-3xl border border-white/10 bg-white/10 p-5 dark:border-zinc-200 dark:bg-zinc-100"><p className="grid size-9 place-items-center rounded-full bg-emerald-400 text-sm font-bold text-zinc-950">{step}</p><h3 className="mt-5 text-xl font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-zinc-300 dark:text-zinc-600">{body}</p></div>)}</div></Panel></section>
      <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6"><div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><Badge>Pricing</Badge><h2 className="mt-4 text-4xl font-semibold tracking-tighter">Pricing for measurable print campaigns, not commodity QR generation.</h2></div><Link href="/dashboard" prefetch={false} className="text-sm font-semibold text-emerald-700 dark:text-emerald-300">Start free</Link></div><div className="grid gap-4 md:grid-cols-4">{plans.map((plan) => <Panel key={plan.id} className={plan.id === "pro" ? "border-emerald-500/50 ring-4 ring-emerald-500/10" : ""}><p className="font-semibold">{plan.name}</p><p className="mt-4 text-4xl font-semibold tracking-tight">${plan.price}<span className="text-sm font-medium text-zinc-500">/mo</span></p><p className="mt-3 min-h-12 text-sm text-zinc-500">{plan.headline}</p><ul className="mt-5 grid gap-2 text-sm">{plan.features.map((feature) => <li key={feature} className="flex gap-2"><Sparkle className="mt-0.5 text-emerald-600" size={15}/>{feature}</li>)}</ul><LinkButton href={plan.price ? `/api/stripe/checkout?plan=${plan.id}` : "/dashboard"} prefetch={false} className="mt-6 w-full">{plan.price ? "Subscribe" : "Start free"}</LinkButton></Panel>)}</div></section>
    </main>
  </div>;
}
